### ISSUE TITLE
Example for memcached setup

### ISSUE THREAD

**Issue by krazyjakee** [MomsFriendlyDevCo/express-middleware-cache#1]
I'm looking for an example with memcached to get me up and running.

**Comment by hash-bang** [comment]
Memcache doesn't really need any options specifying as all the defaults work out of the box as long as the daemon is running.

So it should just be:

```javascript
var emc = require('express-middleware-cache');
// Somewhere in your setup code
emc.setup(done => { ... });

// In an express route
app.get('/api/widgets', emc('30s'), (req, res) => { ... });
```

**Comment by krazyjakee** [comment]
I should have mentioned, I'm using a containerised version of memcached so I will need to specify an IP address and port for memcached. Do they need to be specified in that setup function? That's really the example I was looking for.

**Comment by hash-bang** [comment]
Ah I see.

@momsfriendlydevco/Express-middleware-cache actually uses [@momsfriendlydevco/cache](https://github.com/MomsFriendlyDevCo/generic-cache) behind the scenes to store data so you can pass its config in the `cache` key when setting up the express component.

Something like:

```javascript
var _ = require('lodash');
var emc = require('@momsfriendlydevco/express-middleware-cache');

// Using Lodash's deep setting structure to avoid creating empty objects-within-objects. You could also use _.merge() if you have a lot of config
_.set(emc, 'defaults.cache.memcached.server', '127.0.0.1');

// In an express route
app.get('/api/widgets', emc('30s'), (req, res) => { ... });
```

**Comment by krazyjakee** [comment]
I forgot to thank you for your reply. We are just about to start a huge project potentially using this library so once we are comfortable I will contribute back.

**Comment by hash-bang** [comment]
No problem. Let me know if you have any feedback.

**Comment by krazyjakee** [comment]
I cannot see anything appearing in memcached using this setup.

```javascript
import cache from '@MomsFriendlyDevCo/express-middleware-cache';

cache.defaults.cache = {
  modules: ['memcached'],
  memcached: {
    server: '127.0.0.1:11211'
  }
};
```

**Comment by hash-bang** [comment]
Sorry for not replying sooner, not sure how this one slipped though the cracks.

So is it storing ok with simple tags (just a string) or are you saying the issue here is with any dynamically calculated tag?

**Comment by hash-bang** [comment]
If you run `mocha` inside the module it should run some health checks including one on MemcacheD. Do you see any activity when you do that?

**Comment by krazyjakee** [comment]
Here is my usage on a route (i removed the tags)...

```javascript
expressRouter.get('/:slug', cache('12h'), async (req, res) => {
    const response = await axios(options);
    res.json(response.data);
  });
```

When the cache is initiated with the following configuration...

```
cache.defaults.cache = {
  modules: ['memcached'],
  memcached: {
    server: '127.0.0.1:11211'
  }
};
```

I see this in the terminal...

```
cache Using module memory +0ms
```

I cloned your projects and ran mocha tests and memcached tests are passing 100%

**Comment by krazyjakee** [comment]
Got it!

The solution was to pass the settings here as the defaults are not applied.

```javascript
await util.promisify(global.expressCache.setup)({
    modules: 'memcached',
    memcached: {
      server: '127.0.0.1:11211'
    }
  });
```
