### ISSUE TITLE
Adding route params to tags

### ISSUE THREAD

**Issue by krazyjakee** [MomsFriendlyDevCo/express-middleware-cache#2]
How would I achieve this kind of functionality?

```javascript
router.get('/:slug', cache('1h', { tag: `item-${params.slug}` }), (req, res) => ...
```

Is it possible?

**Comment by hash-bang** [comment]
Good point. I've added the functionality to specify a function / array of functions when specifying tags.

```javascript

**Comment by krazyjakee** [comment]
oh, awesome!

Thanks :D
